### ISSUE TITLE
Factory Method ou Abstract Method

### ISSUE THREAD

**Issue by anjoshigor** [anjoshigor/provas-ufpb-api#5]
Separar o projeto em três camadas view, business e infra. Implementar utilizando
Factory Method ou Abstract Factory a comunicação entre as camadas business e infra.

Sugestão: Criar uma Fábrica de Controladores

**Comment by DiogoDantas** [comment]
Implementar Utilizando Factory Method a comunicação entre as camadas business e infra.

Sugestão: Criar uma Fábrica de Banco de Dados
